### ISSUE TITLE
Fusionauth not handeling username@database in a good fashion. 

### ISSUE THREAD

**Issue by sanderkooger** [FusionAuth/fusionauth-issues#1036]
### Description 
Our first try with fusionauth was an installation on bare metal with an azure backed MySQL database. During this installation we ran into a problem where the database username in the following format (username@database) did not function correctly. 

This error presents itself when using the wizzard at first use, but also when you give the information as ENV Vars to a docker container. 

We hacked around this problem by manually adding the following lines to our ../user/local/fusionauth/fusionauth.properties file 

```
#------------------------------------------------------------------------------
# Database
# - Specify the URL and credentials for your database here
# - Required on each node running FusionAuth App webservice
#------------------------------------------------------------------------------
database.url=jdbc:mysql://XXXXXXXXX-mysql-db.mysql.database.azure.com:3306/fusionauth?serverTimezone=UTC&useSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true
database.username=FusionAuthUserName998@XXXXXXXXXXXXXX-mysql-db
database.password=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

```

This workarround worked but at the moment we are deploying all infra in kubernetes. there we need to set the detais via ENV Vars

When deploying in kubernetes we run into the same problem Fusionauth not accepting the Username@databasename format. The environment var is present and can be echo(ed) in the container. But fusionauth only uses the part before the @ and changes the rest to UserName@%. This causes fusionauth to be unable to authenticate with the database. 

Print out of THE VALUES.YAML field we use for deployment

```
database:
  # database.protocol -- Should either be postgresql or mysql. Protocol for jdbc connection to database
  protocol: mysql
  # database.host -- Hostname or ip of the database instance
  host: "XXXXXXXXXX-mysql-db.mysql.database.azure.com"
  # database.host -- Port of the database instance
  port: 3306
  # database.tls -- Configures whether or not to use tls when connecting to the database
  tls: true
  # database.tlsMode -- If tls is enabled, this configures the mode
  tlsMode: require&verifyServerCertificate=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useSSL=true
  # database.name -- Name of the fusionauth database
  name: fusionauth

  # To use an existing secret, set `existingSecret` to the name of the secret. We expect two keys: `password` and `rootpassword`
  # database.existingSecret -- The name of an existing secret that contains the database passwords
  # existingSecret: ""
  # database.user -- Database username for fusionauth to use in normal operation
  user: "FusionAuthUserName998@XXXXXXXXX-mysql-db"
  # database.password -- Database password for fusionauth to use in normal operation - not required if database.existingSecret is configured
  password: "XXXXXXXXXXXXX"
  # These credentials are used for bootstrapping the database
  root:
    # database.root.user -- Database username for fusionauth to use during initial bootstrap
    user: "FusionAuthUserName998@XXXXXXXXXXX-mysql-db"
    # database.root.password -- Database password for fusionauth to use during initial bootstrap - not required if database.existingSecret is configured
    password: "XXXXXXXXXXXXXXXX"
```

### Affects versions
all versions up to 1.22

### Steps to reproduce
1. pull a docker container or install fusionauth locally
2. Fill out a database username with an @databasename
3. Open the logs and see what database Fusionauth uses
4. See error: Fusionauth does not respect the name@database. 

### Expected behavior
Expecation is Fusionauth to initialize and work with any RFC compliant database username.

### Platform
(Please complete the following information)
 - Device:all
 - OS:ALL
 - Database both mySQL and postgresQL

### Additional context
https://github.com/FusionAuth/fusionauth-issues/issues/94
https://github.com/FusionAuth/fusionauth-issues/issues/95
https://github.com/FusionAuth/fusionauth-issues/issues/681
https://github.com/FusionAuth/fusionauth-issues/issues/1024
