### ISSUE TITLE
Running multiple instances of FusionAuth

### ISSUE THREAD

**Issue by plunkettscott** [FusionAuth/fusionauth-issues#113]
### Description
Is it possible to run multiple instances of FusionAuth? I have a Kubernetes deployment that sets the FUSIONAUTH_URL to my public URL, however, when I run two instances with the same FUSIONAUTH_URL I am constantly logged out of the UI and forced to re-login.

**Comment by whiskerch** [comment]
Are both instances sharing the same database?

If the same DB is being used by both instances then it should work - this page gives more info on configurations: https://fusionauth.io/docs/v1/tech/installation-guide/server-layout

If each instance has its own DB, then as the load balancer is hitting each instance in turn (assuming round robin) it would ask you to re-login as the instance would have no knowledge of the authentication performed by the previous instance.

**Comment by robotdan** [comment]
Thanks @whiskerch ! Love to see the FusionAuth community helping out. @whiskerch is correct, if you have discrete instances of FusionAuth behind the same load balancer, this will behave oddly. :-) 

@plunkettscott Are you trying to build a cluster with multiple nodes or run discrete instances of FusionAuth? 

The `FUSIONAUTH_URL` is really to allow FusionAuth to communicate between nodes within a cluster. This allows one node to tell another node to reload a cache for example.  So this should not be the public URL that you access FusionAuth.

**Comment by plunkettscott** [comment]
Thanks for the quick reply @whiskerch and @robotdan,

Both instances are sharing the same database behind a single service in Kubernetes, which is exposed through an ingress. So, should I leave FUSIONAUTH_URL defaulted and not set it? The problem I see is that the contaienrs get random names when spun up, so creating a cluster where the FUSIONAUTH_URL has to be the specific URL of the server creates issues with using Kubernetes deployments.

Scott

**Comment by robotdan** [comment]
I'm not real K8s smart. But in Docker compose for example, if I had two nodes, I'd have something like this:


```
fusionauth1:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - db
      - search
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USER: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_SEARCH_SERVERS: http://search:9200
      FUSIONAUTH_URL: fusionauth1:9011
    networks:
     - db
     - search
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config

fusionauth2:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - db
      - search
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USER: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_SEARCH_SERVERS: http://search:9200
      FUSIONAUTH_URL: fusionauth2:9011
    networks:
     - db
     - search
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config
```

So the `fusionauth1` service definition has `FUSIONAUTH_URL: fusionauth1:9011` and `fusionauth2` has `FUSIONAUTH_URL: fusionauth2:9011`. 

This will cause the service to store that URL in the database to allow each node to know how to communicate with each other. 

Then you'd access FusionAuth through whatever URL is exposed by ingress. Does that make sense?

**Comment by plunkettscott** [comment]
@robotdan,

Thanks for the example. I've modified it slightly for a more hands-off approach in the Kubernetes deployment, because manually creating new containers to scale up/down is not really what we want to do. I wanted to be able to scale up my deployment as load increases.

Here's the environment config for anyone else who might run into this using Kubernetes.

```yml
 - name: CONTAINER_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
 - name: FUSIONAUTH_URL
    value: $(CONTAINER_NAME):9011
```
