### ISSUE TITLE
Connect to DigitalOcean postgres fails

### ISSUE THREAD

**Issue by hengel2810** [FusionAuth/fusionauth-issues#115]
### Description
I'm currently trying to connect to a managed postgres database from DigitalOcean

These are the env's for the deployment:
```
- name: DATABASE_USER
  value: XXXXX
- name: DATABASE_PASSWORD
  value: XXXXX
- name: DATABASE_ROOT_USER
  value: XXXXX
- name: DATABASE_ROOT_PASSWORD
  value: XXXXX
- name: DATABASE_URL
  value: jdbc:postgresql://fusion-auth-XXXXX.db.ondigitalocean.com:25060/defaultdb?sslmode=require
- name: FUSIONAUTH_MEMORY
  value: 512M
- name: FUSIONAUTH_SEARCH_SERVERS
  value: https://XXXXXX:XXXXX@XXXXXXXXX.eu-central-1.aws.cloud.es.io:9243
```

During start the applications prints the following log:
`Apr 11, 2019 9:02:58.952 PM ERROR com.inversoft.maintenance.db.DatabaseSilentConfigurationWorkflowTask - Silent configuration was unable to complete db configuration. Current state [BAD_CONNECTION]`

Does anyone know what's the problem and is there maybe the possibility to increase the log level ?

**Comment by plunkettscott** [comment]
@hengel2810 

I just spent yesterday evening getting this working with DO Managed Databases from within DO Kubernetes. It looks like you are on the right track. First of all, is the IP address of the server you have FusionAuth installed on added to the list of IPs capable of connecting to the managed database? If not, you'll want to add it. The error (BAD_CONNECTION) looks like a connectivity issue.

**Comment by plunkettscott** [comment]
It's also worth noting that you can't gain superuser access in DO Managed Databases so you'll have to manually import the DB schema from https://fusionauth.io/downloads. You'll never be able to make a successful connection for the root/superuser for FusionAuth to setup the database for you.

**Comment by robotdan** [comment]
Thanks @plunkettscott for helping out on this issue! It is great to see the community support. 

The `BAD_CONNECTION` could mean a few things, but we took an exception while trying to connect.  There are some known issues with using our maintenance mode db configuration with managed database services such as DO. 

We have an open issue to help handle these situations better. This is on the short list to get worked on. https://github.com/FusionAuth/fusionauth-issues/issues/95

I have the work around that @plunkettscott listed in that issue as well. 

One thing you could also try is using the credentials given to you by Digital Ocean in both the super user and the user sections of the configuration. 

If you do find a workaround not listed on the above linked issue do let us know so we can document it. 

Thanks @hengel2810 for taking the time to open the issue to let us know, and thanks @plunkettscott for the assistance as well!

**Comment by hengel2810** [comment]
@plunkettscott @robotdan Thank you for your immediate answers.

With the DO managed database I whitelisted all IP's (bad idea, I know) for testing but it didn't work either. Even if I'm running the manual db setup scripts the error occurs, I think there's a problem during the connection process.
I also tried to connect to a managed database from ElephantSQL and Aiven.io and I got the same error.

I'm using the default k8s from DO in Version 1.13.5 and I added the Nginx Ingress Controller and the cert-manager, anything else is default.

This is my .yml file for the fusion-auth deployment, maybe there's a problem:
```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fusion-auth-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fusion-auth
    spec:
      containers:
        - env:
            - name: DATABASE_PASSWORD
              value: XXX
            - name: DATABASE_ROOT_USER
              value: XXX
            - name: DATABASE_ROOT_PASSWORD
              value: XXX
            - name: DATABASE_URL
              value: jdbc:postgresql://fusion-auth-XXX.aivencloud.com:27769/defaultdb?sslmode=require
            - name: FUSIONAUTH_MEMORY
              value: 512M
            - name: FUSIONAUTH_SEARCH_SERVERS
              value: https://XXX:XXX@XXX.eu-central-1.aws.cloud.es.io:9243
          image: fusionauth/fusionauth-app:1.5.0
          name: fusionauth
          ports:
            - containerPort: 9011
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: fusion-auth-svc
  labels:
    app: fusion-auth
spec:
  type: NodePort
  selector:
    app: fusion-auth
  ports:
    - port: 9011
      targetPort: 9011
```
