### ISSUE TITLE
Create a k8s operator for FusionAuth

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#1572]
### Problem

I want to use FusionAuth as an operator in k8s. More on operators here: https://kubernetes.io/docs/concepts/extend-kubernetes/operator/

### Solution

Make a supported FusionAuth operator.

### Alternatives/workarounds
N/A

### Additional context

Pulling this over from https://github.com/FusionAuth/charts/issues/80

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by kferrone** [comment]
I was tasked with provisioning all the FusionAuth resources into an instance running in k8s. When I saw what I needed to do I couldn't help think this is what Kubernetes operators are for. My only option right now is to use helm hooks to run jobs that CRUD these resources for each 'app' we have. 

I imagine something like this:

```yaml
apiVersion: fusionauth.io/v1
kind: Application
metadata:
  name: my-app
  namespace: default
spec:
... # body of the request from here: https://fusionauth.io/docs/v1/tech/apis/applications/ 
```
