### ISSUE TITLE
wrong port in redirect_uri / fusionauth 1.37+

### ISSUE THREAD

**Issue by MarekUniq** [FusionAuth/fusionauth-issues#2250]
## (Put bug title here)
wrong port in redirect_uri / fusionauth 1.37+

### Description 
Identity Provider login redirect_uri picks wrong port

### Affects versions
fusionauth 1.37+ (up to latest which is 1.45.1 at the moment)

### Steps to reproduce

Start docker image with port mapping 2222:9011

```
--- docker-compose.yml ---
services:
  fusionauth:
    image: fusionauth/fusionauth-app:1.37.2
    ports:
      - 2222:9011
--- docker-compose.yml ---
```

Configure "Google Identity Provider" (possibly any other provider)

Goto URL http://loalhost:2222/admin

Click on "Google Identity Provider" button to log in

Login fails because of wrong redirect_uri: 
redirect_uri=http://localhost:9011/oauth2/callback

Expected redirect_uri:
redirect_uri=http://localhost:2222/oauth2/callback

### Expected behavior
Identity Provider login redirect_uri need to take the port from browser URL (and not the port where the fusionauth web server is technically running inside the fusionauth container)

### Screenshots
Ask if necessary

### Platform
Repeatable:
- inside mac / docker with Postgres 13
- google cloud kubernetes cluster with Postgres 13

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).
