### ISSUE TITLE
Add curl to the docker image

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#2272]
### Problem

Add curl to the docker image so you can use a healthcheck in `docker-compose.yml` to have other services depend on FusionAuth.

### Solution

Install the curl package in the FusionAuth docker image.

### Alternatives/workarounds

1. Not wait for FusionAuth to come up when the container is loaded? 
2. Add in a sleep command?
3. Build your own docker image using the `fusionauth-app` image as a base and add whatever packages you wish. 

### Additional context

Originally posted here: https://github.com/FusionAuth/fusionauth-containers/issues/80

### Related
- https://github.com/FusionAuth/fusionauth-containers/issues/66
- https://github.com/FusionAuth/fusionauth-issues/issues/1044

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

### Release Notes
Add the `curl` command to the FusionAuth Docker image. This allows you to use the `curl` command for use in health checks or anytime you need to use `curl`!

**Comment by robotdan** [comment]
@mooreds are you looking to do something like this from our example `docker-compose.yml` for Elasticsearch?

```
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: search
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    healthcheck:
      test: [ "CMD", "curl",  "--fail" ,"--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://localhost:9200/" ]
      interval: 5s
      timeout: 5s
      retries: 5

 ```
 
 We could do some testing to see how many packages this adds, and measure the delta in image size.
