### ISSUE TITLE
Error while starting fusion auth docker container

### ISSUE THREAD

**Issue by MunishCool** [FusionAuth/fusionauth-issues#2361]
### Description
I am using fusion auth and specified the below properties in my docker-compose.yml file. I am running it using docker-compose up -d and the fusion auth instance is getting created but the container is exiting with the below error. Please suggest a solution to resolve this issue.

## docker-compose.yml

```
fusionauth:
       image: fusionauth/fusionauth-app:latest
       container_name: fusionauth
       restart: always
       environment:
           - DATABASE_URL = jdbc:postgresql://postgres:5432/fusionauth
           - DATABASE_ROOT_USERNAME= <username>
           - DATABASE_ROOT_PASSWORD= <password>
           - DATABASE_USERNAME= <username>
           - DATABASE_PASSWORD= <password>
           - FUSIONAUTH_APP_MEMORY= 512m
           - FUSIONAUTH_APP_RUNTIME_MODE= development
           - FUSIONAUTH_APP_URL= http://fusionauth:9011
           - SEARCH_SERVERS= http://search:9200
           - SEARCH_TYPE= elasticsearch
           - ES_JAVA_OPTS= -Xms512m
       ports:
          - 9011:9011

```
## logs:

Starting fusionauth-app...
  --> Logging to /usr/local/fusionauth/logs/fusionauth-app.log
Invalid maximum heap size: -Xmx
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by robotdan** [comment]
Trying quoting the value

>            - ES_JAVA_OPTS= "-Xms512m"

**Comment by mooreds** [comment]
Can you try removing the extra space after the equals sign?

`- ES_JAVA_OPTS= "-Xms512m"` ->  `- ES_JAVA_OPTS="-Xms512m"`

**Comment by MunishCool** [comment]
Yes, that's working now thanks, but I am facing another issue now.

**Updated docker file:**

```
fusionauth:
       image: fusionauth/fusionauth-app:latest
       container_name: fusionauth
       restart: always
       environment:
           - DATABASE_URL=jdbc:postgresql://postgres:5432/fusionauth
           - DATABASE_ROOT_USERNAME=<username>
           - DATABASE_ROOT_PASSWORD=<password>
           - DATABASE_USERNAME=<username>
           - DATABASE_PASSWORD=<password>
           - FUSIONAUTH_APP_MEMORY=512m
           - FUSIONAUTH_APP_RUNTIME_MODE=development
           - FUSIONAUTH_APP_URL=http://fusionauth:9011
           - SEARCH_SERVERS=http://search:9200
           - SEARCH_TYPE=elasticsearch
           - ES_JAVA_OPTS="-Xms1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
       ports:
          - 9011:9011
```


```
Starting fusionauth-app...
  --> Logging to /usr/local/fusionauth/logs/fusionauth-app.log
[0.012s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /usr/local/fusionauth/fusionauth-app/hs_err_pid1.log
```
