### ISSUE TITLE
Update docker-compose.yml examples using OpenSearch 2.10 as an alternative to Elasticsearch OSS

### ISSUE THREAD

**Issue by Aaron-Ritter** [FusionAuth/fusionauth-issues#2521]
### Problem
There are multiple docker-compose.yml files with elasticsearch:7.17.0 which has [7.17.13 available](https://www.elastic.co/downloads/past-releases#elastic-search) as well a Major upgrade to 8. The major upgrade requires more than just upgrading the version.

There are YAML files but as well documentation sections with 7.17.0 and older versions https://github.com/search?q=org%3AFusionAuth+%22image%3A+docker.elastic.co%2Felasticsearch%2Felasticsearch%22&type=code

### Solution
Investigate to upgrade/migrate to OpenSearch 2.10 instead, with the right configuration settings. Which is supported according to the [documentation](https://fusionauth.io/docs/v1/tech/installation-guide/system-requirements#elasticsearch).

### Alternatives/workarounds
tbd

### Additional context
tbd

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by Aaron-Ritter** [comment]
For a dev setup I've successfully tested the following docker-compose.yml configuration:

- It has security disabled which simplifies the setup drastically
- Same with the use of the single-node setup
- Not sure about `SEARCH_TYPE: elasticsearch` but i assume it's correct as opensearch is used as a replacement for elasticsearch
- Not using `compatibility.override_main_response_version=true` for opensearch

```
version: '3'

services:
  db:
    image: postgres:14
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db_net
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  search:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - node.name=search
      - plugins.security.disabled=true
    healthcheck:
      interval: 10s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    volumes:
      - search_data:/usr/share/opensearch/data
    networks:
      - search_net

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      db:
        condition: service_healthy
      search:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      SEARCH_SERVERS: http://search:9200
      SEARCH_TYPE: elasticsearch

    networks:
      - db_net
      - search_net
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fusionauth_config:/usr/local/fusionauth/config

networks:
  db_net:
    driver: bridge
  search_net:
    driver: bridge

volumes:
  db_data:
  fusionauth_config:
  search_data:
```
