### ISSUE TITLE
Proxy through Google Cloud Load Balancing

### ISSUE THREAD

**Issue by jairojunior** [FusionAuth/fusionauth-issues#2683]
## Proxy through Google Cloud Load Balancing

"FusionAuth should work with any proxy that supports HTTP. If you find a proxy that isn’t supported, please [open a GitHub issue with details](https://github.com/fusionauth/fusionauth-issues/issues)." [1]

### Description
We use FusionAuth on Kubernetes behind an Ingress (ingress-gce) since 2019, but since upgrading to 1.47 we had to add a BackendConfig with a hardcoded value (443) for `X-Forwarded-Port` header, otherwise requests to `/samlv2/sp` included port 9011 in the response.

```yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: fusionauth
spec:
  customRequestHeaders:
    headers:
      - "X-Forwarded-Port:443"
```

Is this expected? Is there a way to fallback to the old behavior, that seemed to default to 443 when `X-Forwarded-Proto` is `https`, and 80 when `http`.

[1] https://fusionauth.io/docs/operate/deploy/proxy-setup#headers-to-set
