### ISSUE TITLE
Initializing FusionAuth without Admin UI

### ISSUE THREAD

**Issue by cowlingj** [FusionAuth/fusionauth-issues#286]
### Problem
After experimenting with FusionAuth I thought it was brilliant, except for the fact that even with advanced installation, I still needed to use the admin UI to set things up on first run. I want to have FusionAuth as a part of a kubernetes cluster and simply deploy it and have things up and running, but I must use the setup wizard before things work.

### Solution
A configuration file (or directory) could be used to automate that original setup, configuration shell scripts would be more flexible, but a yaml file could be sufficient. Something along the lines of:
```yaml
users:
  - firstName: john
    lastName: doe
    email: john@example.com
    password: {{ $JOHN_PASSWORD }}
    marketingEmails: true
applications:
  - id: my-app-id
    name: my-app
    tennant: my-tennant
apiKeys:
  - key: a-long-uuid-looking-string
    description: descriptive text
    tennant: my-tennant
    endpoints:
      - all: # possible shorthand for all endpoints
          - all # possible shorthand for all methods
smtp: {}
licenseAgreed: true
```

The password part can either be handled by accepting some sort of template syntax or as an easier alternative letting the devs/devops handle that (in kubernetes one could use an init-container to write out the configuration file using secrets in environment variables).

> In the case of a configuration directory FusionAuth could process a bunch of scripts in the directory see [mongo docker image docs](https://hub.docker.com/_/mongo#initializing-a-fresh-instance) and [postgres docker image docs](https://hub.docker.com/_/postgres#initialization-scripts)

### Alternatives/workarounds
I don't believe there is currently a way to use FusionAuth without using the UI at all, the [setup wizard section](https://fusionauth.io/docs/v1/tech/tutorials/setup-wizard), seems like a step that requires a manual process, and the [create an application section](https://fusionauth.io/docs/v1/tech/tutorials/create-an-application) only mentions using the UI.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.
