### ISSUE TITLE
[Bug]: [1.56-1.57] FusionAuth starting stuck up on fresh setup using mysql in docker and installing with a .deb

### ISSUE THREAD

**Issue by mavyfaby** [FusionAuth/fusionauth-issues#3013]
### What happened?

I'm installing FusionAuth v1.56 on my Ubuntu 24.10, and when I setup the FusionAuth on maintenance mode on clicking `Submit`. It got stuck forever.

![Image](https://github.com/user-attachments/assets/5aa6056a-167a-4cdd-aac2-cc29ad33e649)

I checked the error logs from `/usr/local/fusionauth/logs/fusionauth-app.log` and nothing unusual. No errors.

### Version

1.56.0-1

### Alternatives / Workarounds

No workarounds, just using FusionAuth 1.55 for now.

## More details

This doesn't occur with a zip file installation on the mac or ubuntu with mysql running in docker. 

It does replicate on Ubuntu linux 24.0 with mysql running in docker. Replication steps:

* stand up an ec2 instance
* install docker (I used https://docs.docker.com/engine/install/ubuntu/ )
* install mysql (I used this docker file with a .env file that looks similar to our default .env file)
```
services:
  db:
    image: mysql:9.2.0
    environment:
      MYSQL_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      MYSQL_DATABASE: 'fusionauth'
      MYSQL_USER: ${POSTGRES_USER}
      MYSQL_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 3306:3306
    networks:
      - db_net
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql

  search:
    image: opensearchproject/opensearch:2.11.0
    environment:
      cluster.name: fusionauth
      discovery.type: single-node
      node.name: search
      plugins.security.disabled: true
      bootstrap.memory_lock: true
      OPENSEARCH_JAVA_OPTS: ${OPENSEARCH_JAVA_OPTS}
    healthcheck:
      interval: 10s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200/
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    volumes:
      - search_data:/usr/share/opensearch/data
    networks:
      - search_net

networks:
  db_net:
    driver: bridge
  search_net:
    driver: bridge

volumes:
  db_data:
  fusionauth_config:
  search_data:
```
* start up mysql and ensure I can connect as the root user using 127.0.0.1: `mysql -h 127.0.0.1 -u root -p<PASS> mysql`
* download fusionauth deb file (1.56.0-1_all.deb) from https://fusionauth.io/direct-download
* run sudo dpkg -i fusionauth-app-1.56.0.deb
* download and install the mysql connector file per https://fusionauth.io/docs/get-started/download-and-install/ database#install-mysql-connector in /usr/local/fusionauth/lib
* start up fusionauth via `sudo systemctl start fusionauth-app`
* fill out the root user/password and the mysql host (127.0.0.1) and try to move out of maintenance mode
* get stuck with the same repeating log files shown in comments below
