### ISSUE TITLE
Issues with UTF-8 for Kickstart included text files

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-issues#510]
### Description 
UTF-8 is properly handled in main Kickstart JSON file, but encoding of included text files is broken.

This behaviour is especially problematic while trying to configure messages translations.

### Steps to reproduce
1. Prepare Kickstart script including a text file containing UTF-8 characters
2. Start Fusionauth
3. See that encoding of included content is broken

### Expected behavior
Included content is correctly encoded

### Platform
 - Device: Desktop
 - OS: 18.04.1-Ubuntu x64
 - Docker: 19.03.6, build 369ce74a3c
 - Image: fusionauth/fusionauth-app:1.15.3

#### Kickstart script fragment:
```json
{
    "body": {
        "user": {
            "firstName": "żółć",
            "lastName": "@{test.json}",
            "password": "12345678",
            "username": "user"
        }
    },
    "url": "/api/user",
    "method": "POST"
}
```
#### `test.json` contents
```
$ cat test.json
źdźbło
```
#### Resulting user
```
$ curl -H "Authorization: *REDACTED*" "http://localhost:9011/api/user?loginId=user" | jq
{
  "user": {
    "active": true,
    "firstName": "żółć",
    "id": "3c4d185b-8af7-4e4f-8019-0de9edf008eb",
    "insertInstant": 1583769427660,
    "lastName": "��d��b��o",
    "passwordChangeRequired": false,
    "passwordLastUpdateInstant": 1583769427765,
    "tenantId": "41908fb2-9099-a3f2-551e-9675119d5e96",
    "twoFactorDelivery": "None",
    "twoFactorEnabled": false,
    "username": "user",
    "usernameStatus": "ACTIVE",
    "verified": true
  }
}
```

**Comment by robotdan** [comment]
I'm unable to recreate. 

What db and version are you using? If MySQL are you using a character set of `utf8mb4` and a collate `utf8mb4_bin`.

What is the locale set in the base environment? Perhaps we are missing an explicit request for UTF-8 bytes.  For example:

```
> env|grep LANG
LANG=en_US.UTF-8
```

**Comment by mgetka** [comment]
I've created example container environment where the issue is present: [mgetka/fusionauth-utf8-issue](https://github.com/mgetka/fusionauth-utf8-issue).

Currently I'm on a different machine, and here fusionauth Fusionauth working environment is different, but the issue not only persist but it is also present for kickstart file itself. Some more info on the environment:

### Host machine:
```
$ uname -a
Linux *** 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ env|grep LANG
LANG=pl_PL.UTF-8
```
### Fusionauth container
```
$ docker exec fusionutf8_fusionauth_1 bash -c "env|grep LANG"
```
(no output)
### Postgres container
```
$ docker exec fusionutf8_db_1 bash -c "env|grep LANG"
LANG=en_US.utf8
```

After the system starts, expected first and last name can be set via GUI and API with no fuss. Maybe the issue is related to the Fusionauth docker image not the application itself?

**Comment by robotdan** [comment]
Thanks @mgetka I was able to recreate with your example. I'll see if I can narrow it down.

**Comment by robotdan** [comment]
I was able to work around the issue by adding `-Dfile.encoding` to the the `ENVIRONMENT` section of the `fusionauth` service. 

```
   fusionauth:
    build: .
    depends_on:
      - db
      - search
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USER: postgres
      DATABASE_ROOT_PASSWORD: postgres
      DATABASE_USER: fusionauth
      DATABASE_PASSWORD: fusionauth
      FUSIONAUTH_SEARCH_SERVERS: http://search:9200
      FUSIONAUTH_ADDITIONAL_JAVA_ARGS: -Dfile.encoding=UTF-8
    ports:
      - 9011:9011
```

This likely means we are missing an explicit request to use UTF-8 somewhere. We'll track it down and correct it in the upcoming patch release. 

Thanks for reporting!
