### ISSUE TITLE
Impossible to access the maintenance mode with v1.16.0-RC.1 on local kubernetes cluster

### ISSUE THREAD

**Issue by zadigus** [FusionAuth/fusionauth-issues#588]
### Description 

I am trying to install fusionauth 1.16.0-RC.1 on my local dev kubernetes cluster without success. The log indicates that we are entering maintenance mode but I can access nothing. Here's the log:

[fusionauth.log](https://github.com/FusionAuth/fusionauth-issues/files/4534631/fusionauth.log)

### Steps to reproduce

On my local kubernetes cluster created on top of docker for desktop, 

1. Create a postgres database with the following helm config:

```yaml
helm:
  chart:
    name: postgresql-ha
    repo: https://charts.bitnami.com/bitnami
  values:
    fullnameOverride: postgres
    persistence:
      enabled: false
    postgresql:
      existingSecret: ${SHARED_DATABASE_SECRET_NAME}
      database: ${DATABASE_NAME}
      username: ${DATABASE_USERNAME}
    volumePermissions:
      enabled: true
```

In essence, this is creating a new postgres instance populated with a database (with name `${DATABASE_NAME}`) and a root user (with name `${DATABASE_USERNAME}`) whose password is stored in the `${SHARED_DATABASE_SECRET_NAME}`. In the `${SHARED_DATABASE_SECRET_NAME}`, I have put the value of environment variable `${DATABASE_PASSWORD}`. Nothing special here.

2. Install fusionauth 1.16.0-RC.1 with [this helm chart](https://gitlab.hidora.com/softozor/shopozor/services/tree/evaluate-fusionauth/backend%2Fauth-service%2Fchart) (there is no official helm chart for fusion auth yet, therefore I created mine) with the following values:
```yaml
image:
  tag: 1.16.0-RC.1
database:
  user: auth
  password: auth
  host: postgres-pgpool
  port: 5432
  name: ${DATABASE_NAME}
  root:
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
ingress:
  enabled: true
  hosts:
    - host: my.auth
      paths:
      - /
```

In essence, this is installing the following fusionauth deployment.yaml:

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fusionauth
  namespace: dev
  labels:
    app.kubernetes.io/instance: fusionauth
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fusionauth
    app.kubernetes.io/version: 1.16.0-RC.1
    helm.sh/chart: fusionauth-0.0.0
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fusionauth
      app.kubernetes.io/name: fusionauth
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: fusionauth
        app.kubernetes.io/name: fusionauth
    spec:
      initContainers:
        - name: wait-for-db
          image: 'darthcabs/tiny-tools:1'
          args:
            - /bin/bash
            - '-c'
            - >
              set -x; while [[ "$(nc -zv 'postgres-pgpool' 5432 &> /dev/null;
              echo $?)" != 0 ]]; do
                echo '.'
                sleep 15;
              done
      containers:
        - name: fusionauth
          image: 'fusionauth/fusionauth-app:1.16.0-RC.1'
          ports:
            - name: http
              containerPort: 9011
              protocol: TCP
          env:
            - name: DATABASE_USER
              value: auth
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fusionauth-credentials
                  key: password
            - name: DATABASE_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fusionauth-credentials
                  key: rootpassword
            - name: DATABASE_ROOT_USER
              value: postgres
            - name: DATABASE_URL
              value: 'jdbc:postgresql://postgres-pgpool:5432/postgres'
            - name: FUSIONAUTH_SEARCH_ENGINE_TYPE
              value: database
            - name: FUSIONAUTH_MEMORY
              value: 256M
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
```

3. Enable port-forwarding for both the database and fusionauth

The fusionauth software seems to misbehave:

1. Upon connection to `localhost:9011`, I get to the maintenance mode (that might be ok, even though I provided the root database username and password with which previous versions of fusionauth were able to directly create everything necessary); when I enter the necessary credentials, then I get this:

![image](https://user-images.githubusercontent.com/8761254/80298694-3f485700-878f-11ea-8809-b34de5fd443b.png)

2. After a while, I cannot connect to the `localhost:9011` any more

Partially the same behavior is observed on my k8s cluster hosted on my Jelastic cloud:

1. I get to the maintenance mode, even though the root database password were provided along with the desired database username and password 

However, upon filling up the form, the fusionauth database gets created and I am routed to the FusionAuth Setup Wizard.

### Expected behavior

I should be able to access the admin panel of fusionauth upon deployment because I have provided everything necessary for that. The fusionauth database and user should be created automatically. I should not even enter the maintenance mode. 

### Platform

 - Device: kubernetes on docker for desktop, jelastic kubernetes cluster
 - OS: irrelevant

**Comment by robotdan** [comment]
Because version 1.16.0-RC.1 is a release candidate, I do not know how it will behave in helm/k8s. 

The error that you show in your screenshot looks to be an auth issue with PostgresQL.

**Comment by zadigus** [comment]
With the [bitnami/postgresql chart](https://github.com/bitnami/charts/tree/master/bitnami/postgresql) installed with the following parameters:
```yaml
fullnameOverride: postgres
persistence:
  enabled: false
postgresqlPassword: postgres
postgresqlDatabase: postgres
volumePermissions:
  enabled: true
```
and the fusionauth app installed with the following parameters:
```yaml
replicaCount: 1
image:
  tag: 1.16.0-RC.1
database:
  user: postgres
  password: postgres
  host: postgres
  port: 5432
  name: fusionauth
  root:
    user: postgres
    password: postgres
ingress:
  enabled: true
  hosts:
  - host: my.auth-local-domain
    paths:
    - /
environment:
  FUSIONAUTH_API_KEY: test
```
it's working like a charm. The only thing that is not working like a charm is that fusionauth does not create the database and the user automatically without presenting me the maintenance mode interface, even though I provide it with all the necessary details.
