### ISSUE TITLE
Cannot login as admin any more after successive logins / logouts on 1.16.0-RC.1 when using k8s

### ISSUE THREAD

**Issue by zadigus** [FusionAuth/fusionauth-issues#590]
### Description 

I was able to successfully install fusionauth version 1.16.0-RC.1 on my remote kubernetes cluster with the following deployment:
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fusionauth
  namespace: auth
  labels:
    app.kubernetes.io/instance: fusionauth
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fusionauth
    app.kubernetes.io/version: 1.16.0-RC.1
    helm.sh/chart: fusionauth-0.0.0
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fusionauth
      app.kubernetes.io/name: fusionauth
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: fusionauth
        app.kubernetes.io/name: fusionauth
    spec:
      volumes:
        - name: fusionauth-config-volume
          configMap:
            name: fusionauth-kickstart-config
            defaultMode: 420
      initContainers:
        - name: wait-for-db
          image: 'darthcabs/tiny-tools:1'
          args:
            - /bin/bash
            - '-c'
            - >
              set -x; while [[ "$(nc -zv 'my-database-hostname'
              5432 &> /dev/null; echo $?)" != 0 ]]; do
                echo '.'
                sleep 15;
              done
      containers:
        - name: fusionauth
          image: 'fusionauth/fusionauth-app:1.16.0-RC.1'
          ports:
            - name: http
              containerPort: 9011
              protocol: TCP
          env:
            - name: DATABASE_USER
              value: auth
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fusionauth-credentials
                  key: password
            - name: DATABASE_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fusionauth-credentials
                  key: rootpassword
            - name: DATABASE_ROOT_USER
              value: webadmin
            - name: DATABASE_URL
              value: 'jdbc:postgresql://my-databasae-hostname:5432/auth'
            - name: FUSIONAUTH_SEARCH_ENGINE_TYPE
              value: database
            - name: FUSIONAUTH_API_KEY
              value: test
            - name: FUSIONAUTH_KICKSTART
              value: /kickstart/kickstart.json
            - name: FUSIONAUTH_MEMORY
              value: 256M
          resources: {}
          volumeMounts:
            - name: fusionauth-config-volume
              mountPath: /kickstart
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
```
After providing some redundant data in the maintenance mode, I finally was able to access the fusionauth instance on my remote cluster. I can even login with the admin credentials provided in my kickstart configuration.

My problem, however, is that I can, with my admin account, login, logout, login, logout, a random amount of times, and then, suddenly, I get unauthorized access, even though nothing changed in my credentials. Is there a work-around? Is this is a bug?

### Steps to reproduce
1. Deploy version 1.16.0-RC.1 to a k8s cluster with kickstart where you define your admin credentials, e.g.
```yaml
    {
        "variables": {
          "defaultTenantId": "d7d09513-a3f5-401c-9685-34ab6c552453",
          "adminEmail": "my-name@my-domain.com",
          "adminPassword": "my-password"
        },
        "apiKeys": [
          {
            "key": "bf69486b-4733-4470-a592-f1bfce7af580",
            "description": "Core API Key"
          }
        ],
        "requests": [
          {
            "method": "POST",
            "url": "/api/user/registration",
            "body": {
              "user": {
                "email": "#{adminEmail}",
                "password": "#{adminPassword}"
              },
              "registration": {
                "applicationId": "#{FUSIONAUTH_APPLICATION_ID}",
                "roles": [
                  "admin"
                ]
              }
            }
          }
        ]
      }
```
2. Login as admin
3. Log out as admin
4. Reproduce steps 2. and 3. as necessary as possible

Then, suddenly, you cannot login any more. You get unauthorized access.

### Expected behavior

I should be able to login / logout as much as I want.

### Platform
 - Device: kubernetes

Strangely, it seems like on Microsoft Edge and Microsoft Internet Explorer, it works all the time. On Chrome, Chrome Incognito, Firefox, and Safari, I get the mysterious unauthorized access after a few login / logouts.
