### ISSUE TITLE
Postgresql database schema creation fails when running w/o elasticsearch.

### ISSUE THREAD

**Issue by mgetka** [FusionAuth/fusionauth-issues#618]
### Description 
Maintenance mode doesn't properly initialize postgresql database when the service is ran without elasticsearch. The issue manifests itself through FusionAuth's runtime user authentication failures while maintenance mode workflow is running. Everything works fine when running with elasticsearch.

### Steps to reproduce
1. Start FusionAuth in development mode with an empty database and without elasticsearch.
2. Observe authentication errors in the database log

### Expected behavior
Database schema is created via maintenance mode.

### Platform
 - Device: Desktop
 - OS: 18.04.2-Ubuntu x64
 - Docker: 19.03.8, build afacb8b7f0
 - Image: fusionauth/fusionauth-app:1.16.0
 - database image: postgres:9.6

### Additional context

Postgresql log entries:
```
fusionauth_1  | ---------------------------------------------------------------------------------------------------------
fusionauth_1  | --------------------------------------- Entering Maintenance Mode ---------------------------------------
fusionauth_1  | ---------------------------------------------------------------------------------------------------------
fusionauth_1  | 
fusionauth_1  | May 10, 2020 6:31:21.934 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Loading FusionAuth configuration file [/usr/local/fusionauth/config/fusionauth.properties]
fusionauth_1  | May 10, 2020 6:31:21.934 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Override property [fusionauth-app.url], set to [http://fusionauth:9011] from ENV.FUSIONAUTH_URL.
fusionauth_1  | May 10, 2020 6:31:21.934 PM INFO  io.fusionauth.api.configuration.PropertiesFileFusionAuthConfiguration - Override property [fusionauth.runtime-mode], set to [Development] from ENV.FUSIONAUTH_RUNTIME_MODE.
fusionauth_1  | May 10, 2020 6:31:21.935 PM INFO  com.inversoft.maintenance.MaintenanceModePoller - Poller started to Wait for configuration to be completed.
fusionauth_1  | 10-May-2020 18:31:21.979 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-9011"]
fusionauth_1  | 10-May-2020 18:31:22.001 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["https-jsse-nio-9013"]
fusionauth_1  | 10-May-2020 18:31:22.010 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-127.0.0.1-9019"]
fusionauth_1  | 10-May-2020 18:31:22.014 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 3177 ms
db_1          | LOG:  incomplete startup packet
db_1          | FATAL:  password authentication failed for user "fusionauth"
db_1          | DETAIL:  Role "fusionauth" does not exist.
db_1          | 	Connection matched pg_hba.conf line 95: "host all all all md5"
db_1          | LOG:  incomplete startup packet
db_1          | FATAL:  password authentication failed for user "fusionauth"
db_1          | DETAIL:  Role "fusionauth" does not exist.
db_1          | 	Connection matched pg_hba.conf line 95: "host all all all md5"
db_1          | LOG:  incomplete startup packet
db_1          | FATAL:  password authentication failed for user "fusionauth"
db_1          | DETAIL:  Role "fusionauth" does not exist.
db_1          | 	Connection matched pg_hba.conf line 95: "host all all all md5"
[...]
```

The problem can be reproduced with the following `docker-compose` file:
```yml
version: "3"

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  #search:
  #  image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
  #  environment:
  #    - cluster.name=fusionauth
  #    - bootstrap.memory_lock=true
  #    - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
  #  restart: unless-stopped
  #  ulimits:
  #    memlock:
  #      soft: -1
  #      hard: -1

  fusionauth:
    image: fusionauth/fusionauth-app:1.16.0
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USER: postgres
      DATABASE_ROOT_PASSWORD: postgres
      DATABASE_USER: fusionauth
      DATABASE_PASSWORD: fusionauth
      #FUSIONAUTH_SEARCH_SERVERS: http://search:9200
      FUSIONAUTH_URL: http://fusionauth:9011
      FUSIONAUTH_RUNTIME_MODE: development
    ports:
      - 9011:9011
```
When elasticsearch related lines are uncommented the service starts correctly.
