### ISSUE TITLE
Can't connect to elastic when starting via docker in production mode

### ISSUE THREAD

**Issue by retendo** [FusionAuth/fusionauth-issues#642]
### Description

It starts in development mode without any problems. I already configured everything while running in development and now wanted to go to production mode.

I try to start FusionAuth in production mode (Docker) but get the following error at some point:
```
fusionauth_1  | May 22, 2020 5:54:37.238 PM INFO  com.inversoft.search.ElasticRestClientHelper - Connecting to Elasticsearch at [http://search:9200]
fusionauth_1  | May 22, 2020 5:54:38.588 PM ERROR io.fusionauth.api.service.search.ElasticsearchSearchEngine - Failed to connect to elastic to identify if index [fusionauth_user] exists.
fusionauth_1  | java.net.ConnectException: Connection refused
fusionauth_1  | 	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:823)
fusionauth_1  | 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:248)
fusionauth_1  | 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
fusionauth_1  | 	at io.fusionauth.api.service.search.ElasticsearchSearchEngine.indexMissingFailHard(ElasticsearchSearchEngine.java:281)
fusionauth_1  | 	at io.fusionauth.api.service.search.ElasticSearchIndexInitializer.<init>(ElasticSearchIndexInitializer.java:32)
fusionauth_1  | 	at io.fusionauth.api.service.search.ElasticSearchIndexInitializer$$FastClassByGuice$$eb6c9fee.newInstance(<generated>)
fusionauth_1  | 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
fusionauth_1  | 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
fusionauth_1  | 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
fusionauth_1  | 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
fusionauth_1  | 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
fusionauth_1  | 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
fusionauth_1  | 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
fusionauth_1  | 	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
fusionauth_1  | 	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
fusionauth_1  | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
fusionauth_1  | 	at com.google.inject.Guice.createInjector(Guice.java:87)
fusionauth_1  | 	at com.google.inject.Guice.createInjector(Guice.java:69)
fusionauth_1  | 	at com.google.inject.Guice.createInjector(Guice.java:59)
fusionauth_1  | 	at org.primeframework.mvc.guice.GuiceBootstrap.initialize(GuiceBootstrap.java:58)
fusionauth_1  | 	at org.primeframework.mvc.servlet.PrimeServletContextListener.contextInitialized(PrimeServletContextListener.java:61)
fusionauth_1  | 	at com.inversoft.maintenance.servlet.MaintenanceModePrimeServletContextListener.contextInitialized(MaintenanceModePrimeServletContextListener.java:46)
fusionauth_1  | 	at io.fusionauth.app.primeframework.FusionAuthAppPrimeServletContextListener.contextInitialized(FusionAuthAppPrimeServletContextListener.java:28)
fusionauth_1  | 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4701)
fusionauth_1  | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5167)
fusionauth_1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
fusionauth_1  | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)
fusionauth_1  | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)
fusionauth_1  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
fusionauth_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
fusionauth_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
fusionauth_1  | 	at java.base/java.lang.Thread.run(Thread.java:832)
fusionauth_1  | Caused by: java.net.ConnectException: Connection refused
fusionauth_1  | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
fusionauth_1  | 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:589)
fusionauth_1  | 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:839)
fusionauth_1  | 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
fusionauth_1  | 	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
fusionauth_1  | 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
fusionauth_1  | 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
fusionauth_1  | 	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
fusionauth_1  | 	... 1 common frames omitted
fusionauth_1  | May 22, 2020 5:54:39.064 PM ERROR org.primeframework.mvc.guice.GuiceBootstrap - 
fusionauth_1  | 
fusionauth_1  | ===================================================================================================
fusionauth_1  | 
fusionauth_1  |   Unable to start the server. Here's why: 
fusionauth_1  | 
fusionauth_1  | 
fusionauth_1  | [Error injecting constructor, com.inversoft.search.SearchEngineIOException: java.net.ConnectException: Connection refused] 
fusionauth_1  | 	-> [class com.inversoft.search.SearchEngineIOException] java.net.ConnectException: Connection refused
fusionauth_1  | 
fusionauth_1  | ===================================================================================================
```

### Steps to reproduce
I started with `docker compose up` using the following files:

docker-compose.yml
```
version: '3'

services:
  fusionauth:
    image: fusionauth/fusionauth-app:1.16.1
    environment:
      DATABASE_URL: jdbc:postgresql://xxxxxxxxxxmydb-connectionxxxxxx
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_SEARCH_ENGINE_TYPE: database
      FUSIONAUTH_URL: http://fusionauth:9011
      FUSIONAUTH_RUNTIME_MODE: production
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config

volumes:
  fa_config:

```

docker-compose.override.yml (didn't change anything here, I think)
```
version: '3'

services:

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    # Un-comment to access the search service directly
    # ports:
    #  - 9200:9200
    #  - 9300:9300
    networks:
      - search
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data

  fusionauth:
    depends_on:
      - search
    environment:
      FUSIONAUTH_SEARCH_ENGINE_TYPE: elasticsearch
      FUSIONAUTH_SEARCH_SERVERS: http://search:9200
    networks:
      - search

networks:
  search:
    driver: bridge

volumes:
  es_data:
```

### Platform
Ubuntu 18.04
