### ISSUE TITLE
Error 401, Fusion Failed to access ElasticSearch 

### ISSUE THREAD

**Issue by oliverwreath** [FusionAuth/fusionauth-issues#687]
### Description 
Fusion failed to connect to ElasticSearch, with the ElasticSearch's built-in basic authentication turned on. 

### Steps to reproduce

1. Run the commands from the "Using FusionAuth with Docker-compose" guide: 

```Shell
curl -o docker-compose.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.yml
curl -o docker-compose.override.yml https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/docker-compose.override.yml
curl -o .env https://raw.githubusercontent.com/FusionAuth/fusionauth-containers/master/docker/fusionauth/.env
```

2. Add these ElasticSearch Environments:
![image](https://user-images.githubusercontent.com/3938171/84851981-aebd2300-b029-11ea-89be-7680c6a1de8a.png)

```YAML
  elastic:
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      xpack.security.enabled: "true"
```

3. docker-compose up

### Expected behavior 
It shall take these Environments, and connect to the ElasticSearch successfully: 

```YAML
  fusionAuth: 
    environment: 
      ELASTIC_SECURITY_ENABLED: "true" 
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
```

### Screenshots
![image](https://user-images.githubusercontent.com/3938171/84851268-d3180000-b027-11ea-88ad-e3fa98d12f8c.png)

### Platform
(Please complete the following information)
 - Device: Server
 - OS:       CentOS 7.8
 - Browser + version   SSH

### Additional context
N/A
