### ISSUE TITLE
Configuration crash after update to v1.19

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#847]
### Description 

After upgrading to v1.19, some already setup configuration was ignored and/or cause crashes:

- The `FUSIONAUTH_SEARCH_SERVERS` env var defining the elastic search server to contact is now ignored. We had to manually change the `fusionauth-app.search-servers` to `http://app-search:9200` on the `/usr/local/fusionauth/config/fusionauth.properties` file.
- The current `FUSIONAUTH_URL` env var (with value: `http://app:9011`) is not used by the starter wizard causing a complete crash of the application.

I didn't see anything related on your release note.

Can you please clarify if we had to change anything on our configuration since v1.19?

### Affects versions

v1.19

### Steps to reproduce

Update from v1.18 to v1.19.

### Expected behavior

A working app. :upside_down_face: 

### Platform
(Please complete the following information)
 - Device: Not relevant.
 - OS: Linux + Docker
 - Browser + version Not relevant.
 - Database PostgresSQL

### Additional context

Maybe related to #846 but the error description is not quite the same.

Before upgrade, we made a fresh docker deployment of our update merge request starting from nothing. The app was working great.

I suspect an issue on our migration system.

The current `app` definition on our `docker-compose.yml`:

```
services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build:
      context: .
      target: app
    depends_on:
      - search
    environment:
      DATABASE_URL: jdbc:postgresql://${CI_PROJECT_PATH_SLUG}-db:5432/${DATABASE_NAME}
      DATABASE_ROOT_USER: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_SEARCH_SERVERS: http://${CI_PROJECT_PATH_SLUG}-search:9200
      FUSIONAUTH_URL: http://app:9011
    volumes:
      - config:/usr/local/fusionauth/config
    networks:
      default: ~
      internal:
        aliases:
          - ${CI_PROJECT_PATH_SLUG}-app
```
