### ISSUE TITLE
Silent mode on 1.19.0+ and MySQL may fail

### ISSUE THREAD

**Issue by robotdan** [FusionAuth/fusionauth-issues#849]
### Description 
It is unclear if this is a bug in FusionAuth or the db configuration.But a user expererienced the following after updating to 1.19.1. 

```
java.lang.IllegalStateException: Unable to capture database lock. This indicates that the database either doesn't support locks or is misconfigured
```

In version >= 1.19.0 we support silent mode db upgrades even when using runtime mode `production`. This allows FusionAuth optionally handle the db schema updates even in a production multi-node environment. 

In MySQL we do this with a db lock, obtained using the following statement:

```
SELECT GET_LOCK('fusionauth-maintenance-mode', -1);
```

This MySQL function has been around at least since 5.6, I didn't look at older documentation. In this case the user is on version `8.0.21`. 

https://dev.mysql.com/doc/refman/8.0/en/locking-functions.html#function_get-lock

We throw the `IllegalStateException` because the `SELECT` statement did not return a result, or the result was not equal to `1`. 

### Affects versions
1.19.0+

### Steps to reproduce
Using MySQL

Update from pre 1.19.0 to 1.19.0 or 1.19.1 using silent mode in runtime mode for `development` or `production`. If in `production` runtime mode you'll need to also explicitly enable silent mode by using environment variable `FUSIONAUTH_APP.SILENT_MODE=true` or adding `fusionaut-app.silent-mode=true` to your `fusionauth.properties` file. 

### Expected behavior
No error, for the db lock to work. 

### Platform
MySQL version 8.0.21

**Comment by markschmid** [comment]
Here's just a little more context:

FA and the database are both run as a Docker container.

If I manually connect to the fusionauth database using the same credentials used in the docker compose files (```DATABASE_USERNAME``` and ```DATABASE_PASSWORD```) and run ```SELECT GET_LOCK('fusionauth-maintenance-mode', -1);```, I get 1 as a response. If I run ```SELECT RELEASE_LOCK('fusionauth-maintenance-mode');```, I get 1 as well. If I run the release command again, I get NULL. So this locking business seems to work in general, on this database instance.

**Comment by robotdan** [comment]
@markschmid is this a single node configuration of FusionAuth?

**Comment by markschmid** [comment]
@robotdan Yes, it's a single node configuration on Docker. These are the env vars that are used:
```
    environment:
      DATABASE_URL: jdbc:mysql://database:3306/fusionauth?serverTimezone=CET
      DATABASE_ROOT_USER: root
      DATABASE_ROOT_PASSWORD: <rootpw>
      DATABASE_USERNAME: fusionauth
      DATABASE_PASSWORD: <fusionauthpw>
      FUSIONAUTH_APP_MEMORY: 256M
      FUSIONAUTH_APP_URL: http://fusionauth:9011
      FUSIONAUTH_APP_RUNTIME_MODE: development
      SEARCH_TYPE: database
```
