### ISSUE TITLE
FusionAuth Docker image is leaking memory

### ISSUE THREAD

**Issue by dav1app** [FusionAuth/fusionauth-issues#907]
@mooreds, sorry for marking you here, but as you asked to hear about that I'm encountering, here we go:

### How to:
1) Launch the Docker image available on the site. 
2) What the memory usage increase from arround 200mb to 1GB without doing absolutely anything with the server. The code below shows the memory usage at this time. Only the initial setup for the account was done, no access, no usage, just the setup.
3) In 2 days, the server will stop responding, SSH access will be limited with memory errors. 

``` 
# free -m

              total        used        free      shared  buff/cache   available
Mem:        1004892      793180       77096       16520      134616       60940
Swap:             0           0           0
```
```
# top

top - 01:10:38 up 1 day,  9:01,  2 users,  load average: 0.01, 0.35, 0.80
Tasks: 125 total,   1 running, 124 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.3 us,  1.0 sy,  0.0 ni, 96.3 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
MiB Mem :    981.3 total,     62.3 free,    787.0 used,    132.1 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.     47.1 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                    
    687 root      20   0  776904  24432    372 S   1.0   2.4   3:24.92 containerd                                                                                                                                                 
   7124 root      20   0  828868  50084   1648 S   1.0   5.0   2:06.63 dockerd                                                                                                                                                    
  16088 1000      20   0 1943244 527380      0 S   0.7  52.5   4:58.96 java                                                                                                                                                       
  61935 70        20   0  194308  12072   9608 S   0.3   1.2   0:00.01 postgres                                                                                                                                                   
  62078 root      20   0   11416   4056   3360 R   0.3   0.4   0:00.04 top                                                                                                                                                        
      1 root      20   0  169612   8772   4160 S   0.0   0.9   0:11.17 systemd                                                                                                                                                    
      2 root      20   0       0      0      0 S   0.0   0.0   0:00.01 kthreadd        
```
This `top` command shows the `java` process below: 

```
# cat /proc/16088/cmdline

/opt/openjdk//bin/java--add-opens=java.base/java.lang=ALL-UNNAMED--add-opens=java.base/java.io=ALL-UNNAMED--add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED-Djava.util.logging.config.file=/usr/local/fusionauth/fusionauth-app/apache-tomcat/conf/logging.properties-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager-Djava.awt.headless=true-Dcom.sun.org.apache.xml.internal.security.ignoreLineBreaks=true-Dnashorn.args=--no-deprecation-warning--enable-preview-Dfusionauth-app.http.port=9011-Dfusionauth-app.https.port=9013-Dfusionauth-app.ajp.port=9019-Dfusionauth-app.management.port=9010-Djdk.tls.ephemeralDHKeySize=2048-Djava.protocol.handler.pkgs=org.apache.catalina.webresources-Dorg.apache.catalina.security.SecurityListener.UMASK=0027-Dfusionauth.home.directory=/usr/local/fusionauth/fusionauth-app/apache-tomcat/..-Dfusionauth.config.directory=/usr/local/fusionauth/fusionauth-app/apache-tomcat/../../config-Dfusionauth.log.directory=/usr/local/fusionauth/fusionauth-app/apache-tomcat/../../logs-Dfusionauth.plugin.directory=/usr/local/fusionauth/fusionauth-app/apache-tomcat/../../plugins-Xmx336M-Xms336M-Dignore.endorsed.dirs=-classpath/usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/bootstrap.jar:/usr/local/fusionauth/fusionauth-app/apache-tomcat/bin/tomcat-juli.jar-Dcatalina.base=/usr/local/fusionauth/fusionauth-app/apache-tomcat-Dcatalina.home=/usr/local/fusionauth/fusionauth-app/apache-tomcat-Djava.io.tmpdir=/usr/local/fusionauth/fusionauth-app/apache-tomcat/temporg.apache.catalina.startup.Bootstrapstart
```

This is the full docker-compose.yml file. I've changed the names of the services and added Traefiks routing to match system requirements. 
```
version: "3"

services:
  v5prrx6868zmfq5:
    image: postgres:11.9-alpine
    container_name: v5prrx6868zmfq5
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - v5prrx6868zmfq5
    restart: unless-stopped
    volumes:
      - v5prrx6868zmfq5_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 336M

  6pdfxyau43dwm6k:
    image: fusionauth/fusionauth-app:latest
    container_name: 6pdfxyau43dwm6k
    depends_on:
      - v5prrx6868zmfq5
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_ROOT_USER: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: ${FUSIONAUTH_APP_URL}
      SEARCH_TYPE: database
    labels:
      - name=name
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.services.6pdfxyau43dwm6k.loadbalancer.server.port=9011
      - traefik.http.routers.6pdfxyau43dwm6k.entrypoints=websecure
      - traefik.http.routers.6pdfxyau43dwm6k.tls=true
      - traefik.http.routers.6pdfxyau43dwm6k.tls.certresolver=resolver1
      - traefik.http.routers.6pdfxyau43dwm6k.tls.domains[0].main=***
      - traefik.http.routers.6pdfxyau43dwm6k.rule=Host(`***`)
    networks:
      - v5prrx6868zmfq5
      - traefik_default
    restart: unless-stopped
    volumes:
      - 6pdfxyau43dwm6k_config:/usr/local/fusionauth/config
    deploy:
      resources:
        limits:
          memory: 336M

networks:
  v5prrx6868zmfq5:
    driver: bridge
  traefik_default:
    external: true
volumes:
  v5prrx6868zmfq5_data:
  6pdfxyau43dwm6k_config:
```
The `memory` tag from above was deployed using `docker-compose --compatibility up`. 

### OS
I've tested on both RancherOS and Ubuntu-Docker image, locally and over Digital Ocean. 

### Important notes

- I've been using Traefik to route the traffic from the server, but it seems to be unrelated to the issue.
- The ideal scenario for me is to use 336MB of RAM, so I've tried `336m` and the default `512m`. The `ES_JAVA_OPTS` option seems to not be useful because I'm not using ElasticSearch. The version that I'm running is `1.19.8`. 
```
ES_JAVA_OPTS=-Xms336m -Xmx336m
FUSIONAUTH_MEMORY=336M
FUSIONAUTH_APP_MEMORY=336M
```
```
ES_JAVA_OPTS=-Xms512m -Xmx512m
FUSIONAUTH_MEMORY=512M
FUSIONAUTH_APP_MEMORY=512M
```

**Comment by mooreds** [comment]
@davimello28 thanks for explaining your setup.

Original comment: https://github.com/FusionAuth/fusionauth-issues/issues/78#issuecomment-702373206

**Comment by mooreds** [comment]
OK. So I set up the docker compose yml file. I modified it a bit so I could get through the setup (because my network config is different, of course). I also removed the traefik network. Here it is:

```
version: "3"

services:
  v5prrx6868zmfq5:
    image: postgres:11.9-alpine
    container_name: v5prrx6868zmfq5
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - v5prrx6868zmfq5
    restart: unless-stopped
    volumes:
      - v5prrx6868zmfq5_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 336M

  6pdfxyau43dwm6k:
    image: fusionauth/fusionauth-app:1.19.8
    container_name: 6pdfxyau43dwm6k
    depends_on:
      - v5prrx6868zmfq5
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_ROOT_USER: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: ${FUSIONAUTH_APP_URL}
      FUSIONAUTH_APP_ADDITIONAL_JAVA_ARGS: ${FUSIONAUTH_APP_ADDITIONAL_JAVA_ARGS}
      SEARCH_TYPE: database
    labels:
      - name=name
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.services.6pdfxyau43dwm6k.loadbalancer.server.port=9011
      - traefik.http.routers.6pdfxyau43dwm6k.entrypoints=websecure
      - traefik.http.routers.6pdfxyau43dwm6k.tls=true
      - traefik.http.routers.6pdfxyau43dwm6k.tls.certresolver=resolver1
      - traefik.http.routers.6pdfxyau43dwm6k.tls.domains[0].main=***
      - traefik.http.routers.6pdfxyau43dwm6k.rule=Host(`***`)
    networks:
      - v5prrx6868zmfq5
    restart: unless-stopped
    ports:
      - 9111:9011
      - 9119:9019
    volumes:
      - 6pdfxyau43dwm6k_config:/usr/local/fusionauth/config
    deploy:
      resources:
        limits:
          memory: 336M

networks:
  v5prrx6868zmfq5:
    driver: bridge
volumes:
  v5prrx6868zmfq5_data:
  6pdfxyau43dwm6k_config:
```

and I start it with this script:

```
export POSTGRES_USER=postgres
export POSTGRES_PASSWORD=postgres
export DATABASE_USER=fusionauth
export DATABASE_PASSWORD=fusionauth
export DATABASE_URL=jdbc:postgresql://v5prrx6868zmfq5:5432/fusionauth
export FUSIONAUTH_MEMORY=336M
export FUSIONAUTH_APP_ADDITIONAL_JAVA_ARGS="-XX:+PrintFlagsFinal "
docker-compose up
```

I'm running it on port 9111 so I can check it out on Monday. All I did was login to the admin account. The docker tag I pulled was 1.19.8 (same as you). I'm running on a mac with `Docker version 19.03.12, build 48a66213fe`. I'll be checking the memory with `docker stats <containerid>` as that's a bit easier than top.

We use openjdk 14 ( https://github.com/FusionAuth/fusionauth-containers/blob/master/docker/fusionauth/fusionauth-app/Dockerfile ). I did check and tomcat is being started up with the `-Xmx336m -Xms336m` arguments, which is what you were seeing too.
