### ISSUE TITLE
Kickstart message changed

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-issues#957]
### Description 

There's a change in the kickstart message when I run it on macOS 10.15.7

It used to show a little hand emoji, now it just has a question mark.

```
fusionauth_1  | ---------------------------------------------------------------------------------------------------------
fusionauth_1  | -------------------------------------------- Kickstarting ? --------------------------------------------
fusionauth_1  | ---------------------------------------------------------------------------------------------------------

```

### Affects versions

1.20

### Steps to reproduce
1. Stand up a docker instance and use kickstart file (sample file attached, instructions on how to use docker/kickstart here: https://fusionauth.io/community/forum/topic/255/how-can-you-use-kickstart-with-docker )
1. Look at the output of the log

### Expected behavior

I'd see the hand emoji.

### Additional context

I don't know if this is a big issue, I'd just worry about it being a canary in a coal mine for encoding handling issues.

docker compose

```
version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      PGDATA: /var/lib/postgresql/data00758/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
# Un-comment to access the db service directly
#    ports:
#      - 5432:5432
    networks:
      - db
    restart: unless-stopped
    volumes:
      - db_data00758:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USER: postgres
      DATABASE_ROOT_PASSWORD: postgres
      DATABASE_USER: fa_123
      DATABASE_PASSWORD: fa_123
      FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_SEARCH_ENGINE_TYPE: elasticsearch
      FUSIONAUTH_URL: http://fusionauth:9011
      FUSIONAUTH_RUNTIME_MODE: production
      FUSIONAUTH_KICKSTART: ${FUSIONAUTH_KICKSTART}
    networks:
     - db
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config00758:/usr/local/fusionauth/config
      - ./kickstart:/usr/local/fusionauth/kickstart

networks:
  db:
    driver: bridge

volumes:
  db_data00758:
  fa_config00758:
```

docker-compose override

```
version: '3'

services:

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    # Un-comment to access the search service directly
    # ports:
    #  - 9200:9200
    #  - 9300:9300
    networks:
      - search
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data4:/usr/share/elasticsearch/data

  fusionauth:
    depends_on:
      - search
    environment:
      # Prior to version 1.19.0, use these deprecated variables
      # FUSIONAUTH_SEARCH_ENGINE_TYPE: elasticsearch
      # FUSIONAUTH_SEARCH_SERVERS: http://search:9200
      SEARCH_SERVERS: http://search:9200
      SEARCH_TYPE: elasticsearch
    networks:
      - search

networks:
  search:
    driver: bridge

volumes:
  es_data4:
```

kickstart.json

```
{
  "variables": {
    "adminEmail": "admin@example.com",
    "password": "password",
    "defaultTenantId": "30663132-6464-6665-3032-32646661393"
  },
  "apiKeys": [
    {
      "key": "SNjNZj8jz4A_5BeL07pF901nwlLxRQ3CK6shpuIFQkg",
      "description": "Standard development API key"
    }
  ],
  "supportId": "xxxx",
  "requests": [
    {
      "method": "PATCH",
      "url": "/api/system-configuration",
      "body": {
        "systemConfiguration": {
          "corsConfiguration": {
            "allowedMethods": [
              "GET", "POST", "PUT", "DELETE",
              "HEAD", "OPTIONS", "PATCH"
            ],
            "allowedOrigins": ["*"]
          }
        }
      }
    },
    {
      "method": "POST",
      "url": "/api/application/30663132-6464-6665-3032-32646661300",
      "body": {
        "application": {
          "name": "LOEN",
          "roles": [
            {
              "name": "loenadmin",
              "isDefault": false,
              "isSuperRole": true
            },
            {
              "name": "operator",
              "isDefault": true,
              "isSuperRole": false
            }
          ],
          "jwtConfiguration": {
            "enabled": true,
            "refreshTokenTimeToLiveInMinutes": 43200,
            "timeToLiveInSeconds": 3600
          }
        }
      }
    },
    {
      "method": "POST",
      "url": "/api/user/registration/00000000-0000-0000-0000-000000000001",
      "body": {
        "user": {
          "firstName": "FusionAuth",
          "lastName": "SuperAdmin",
          "email": "#{adminEmail}",
          "password": "#{password}"
        },
        "registration": {
          "applicationId": "#{FUSIONAUTH_APPLICATION_ID}",
          "roles": ["admin"]
        }
      }
    }
  ]
}

```

startdocker.sh

```
export FUSIONAUTH_KICKSTART=/usr/local/fusionauth/kickstart/kickstart.json
export FUSIONAUTH_MEMORY=512M
docker-compose up

```
