### ISSUE TITLE
Fixtures provider

### ISSUE THREAD

**Issue by soullivaneuh** [FusionAuth/fusionauth-issues#989]
### Problem

I am currently deploying staging instances of my FusionAuth application and many front projects rely on.

In order to integrate oauth connection on front staging instance and e2e tests, I would like to ensure the same data set of users/applications/api-keys (not exhaustive) are set.

### Solution

Provide a way to define fixtures by files. Something like this:

```yaml
users:
  user_default:
    username: user_default
    email: user.default@example.com

applications:
# ...
```

### Alternatives/workarounds

I made create SQL queries directly to the database to achieve that.

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.
